export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';

export const UPDATE_ABOUT_SUCCESS = 'UPDATE_ABOUT_SUCCESS';

export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';

export const CHANGE_IS_PUBLIC_VIEW = 'CHANGE_IS_PUBLIC_VIEW';

export const UPDATE_PLACE_OF_WORK = 'UPDATE_PLACE_OF_WORK';

export const UPDATE_PROFILE_CITY = 'UPDATE_PROFILE_CITY';
