export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const UPDATE_ABOUT_START = 'UPDATE_ABOUT_START';
export const UPDATE_ABOUT_SUCCESS = 'UPDATE_ABOUT_SUCCESS';
export const UPDATE_ABOUT_FAILURE = 'UPDATE_ABOUT_FAILURE';

export const CHANGE_IS_PUBLIC_VIEW = 'CHANGE_IS_PUBLIC_VIEW';
