export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';

export const UPDATE_ABOUT_SUCCESS = 'UPDATE_ABOUT_SUCCESS';

export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';

export const CHANGE_IS_PUBLIC_VIEW = 'CHANGE_IS_PUBLIC_VIEW';
