export const GET_APPOINTMENTS_START = 'GET_APPOINTMENTS_START';
export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_FAILURE = 'GET_APPOINTMENTS_FAILURE';

export const SET_APPOINTMENT_DATE = 'SET_APPOINTMENT_DATE';
export const UNSET_APPOINTMENT_DATE = 'UNSET_APPOINTMENT_DATE';

export const SET_APPOINTMENT_SERVICE = 'SET_APPOINTMENT_SERVICE';
export const UNSET_APPOINTMENT_SERVICE = 'UNSET_APPOINTMENT_SERVICE';

export const UNSET_APPOINTMENT = 'UNSET_APPOINTMENT';
export const BOOK_APPOINTMENT_SUCCESS = 'BOOK_APPOINTMENT_SUCCESS';
