export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';

export const SET_APPOINTMENT_DATE = 'SET_APPOINTMENT_DATE';
export const UNSET_APPOINTMENT_DATE = 'UNSET_APPOINTMENT_DATE';

export const SET_APPOINTMENT_SERVICE = 'SET_APPOINTMENT_SERVICE';
export const UNSET_APPOINTMENT_SERVICE = 'UNSET_APPOINTMENT_SERVICE';

export const UNSET_APPOINTMENT = 'UNSET_APPOINTMENT';
export const BOOK_APPOINTMENT_SUCCESS = 'BOOK_APPOINTMENT_SUCCESS';

export const SET_APPOINTMENTS = 'SET_APPOINTMENTS';

export const CHANGE_APPOINTMENT_STATUS = 'CHANGE_APPOINTMENT_STATUS';

// upsert review to appointment
export const UPSERT_APPOINTMENT_REVIEW = 'UPSERT_APPOINTMENT_REVIEW';
