export const GET_MESSAGE_FROM_INTERLOCUTOR = 'GET_MESSAGE_FROM_INTERLOCUTOR';
export const SET_MESSAGES_VIEWED_BY_RECIPIENT = 'SET_MESSAGES_VIEWED_BY_RECIPIENT';
export const SET_ONLINE_STATUS = 'SET_ONLINE_STATUS';
export const BOOK_APPOINTMENT_BY_CUSTOMER = 'BOOK_APPOINTMENT_BY_CUSTOMER';
export const CHANGE_APPOINTMENT_STATUS_SOCKET = 'CHANGE_APPOINTMENT_STATUS_SOCKET';
export const UPDATE_APPOINTMENT_TO_UNSUITABLE_SOCKET = 'UPDATE_APPOINTMENT_TO_UNSUITABLE_SOCKET';
