// export const GET_TIMETABLE_START = 'GET_TIMETABLE_START';
export const GET_TIMETABLE_SUCCESS = 'GET_TIMETABLE_SUCCESS';
export const GET_TIMETABLE_FAILURE = 'GET_TIMETABLE_FAILURE';

// export const GET_TIMETABLE_AND_APPOINTMENTS_START = 'GET_TIMETABLE_AND_APPOINTMENTS_START';
// export const GET_TIMETABLE_AND_APPOINTMENTS_SUCCESS = 'GET_TIMETABLE_AND_APPOINTMENTS_SUCCESS';
// export const GET_TIMETABLE_AND_APPOINTMENTS_FAILURE = 'GET_TIMETABLE_AND_APPOINTMENTS_FAILURE';

export const SET_TIMETABLE_UPDATE = 'SET_TIMETABLE_UPDATE';
export const UNSET_TIMETABLE_UPDATE = 'UNSET_TIMETABLE_UPDATE';
// export const GET_TIMETABLE_FAILURE = 'GET_TIMETABLE_FAILURE';
