export const BACK_TO_TIMETABLE = 'BACK_TO_TIMETABLE';
export const BACK_TO_SERVICES = 'BACK_TO_SERVICES';
export const PICK_SERVICE = 'PICK_SERVICE';
export const PICK_DATE = 'PICK_DATE';
export const FROM_RESULT_TO_TIMETABLE = 'FROM_RESULT_TO_TIMETABLE';
export const FROM_RESULT_TO_SERVICES = 'FROM_RESULT_TO_SERVICES';
export const UNSET_APPOINTMENT = 'UNSET_APPOINTMENT';
export const GO_TO_SUCCESS = 'GO_TO_SUCCESS';
