export const REODER_SERVICES = 'REODER_SERVICES';
export const REODER_SUB_SERVICES = 'REODER_SUB_SERVICES';
export const SET_INITIAL_ORDER = 'SET_INITIAL_ORDER';

export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';

export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';

export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';

export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';

export const PUT_UPDATE_TO_SERVICES = 'PUT_UPDATE_TO_SERVICES';

export const SERVICES_TO_UNSUITABLE = 'SERVICES_TO_UNSUITABLE';

export const DELETE_SERVICES_UPDATE = 'DELETE_SERVICES_UPDATE';
