export const GET_WORKS_START = 'GET_WORKS_START';
export const GET_WORKS_SUCCESS = 'GET_WORKS_SUCCESS';
export const GET_WORKS_FAILURE = 'GET_WORKS_FAILURE';

export const ADD_WORK_START = 'ADD_WORK_START';
export const ADD_WORK_SUCCESS = 'ADD_WORK_SUCCESS';
export const ADD_WORK_FAILURE = 'ADD_WORK_FAILURE';

export const UPDATE_WORK_START = 'UPDATE_WORK_START';
export const UPDATE_WORK_SUCCESS = 'UPDATE_WORK_SUCCESS';
export const UPDATE_WORK_FAILURE = 'UPDATE_WORK_FAILURE';

export const DELETE_WORK_START = 'DELETE_WORK_START';
export const DELETE_WORK_SUCCESS = 'DELETE_WORK_SUCCESS';
export const DELETE_WORK_FAILURE = 'DELETE_WORK_FAILURE';
