export const GET_WORKS_SUCCESS = 'GET_WORKS_SUCCESS';

export const ADD_WORK_SUCCESS = 'ADD_WORK_SUCCESS';

export const UPDATE_WORK_SUCCESS = 'UPDATE_WORK_SUCCESS';

export const DELETE_WORK_SUCCESS = 'DELETE_WORK_SUCCESS';
